Repository openshift/lightspeed-console, pull requests merged in 2024-08, with the labels that each got.

#302 Remove mention of Cypress from README
  README.md
Labels: lgtm, approved

#303 Remove Dockerfile.lint that is not being used
  Dockerfile.lint
Labels: lgtm, approved

#306 Fix formatting of 2 errors logged to the browser console
  src/components/Popover.tsx
  src/components/ReadinessAlert.tsx
Labels: lgtm, approved

#308 OLS-831: Expand eslint rules
  .eslintrc.yml
  locales/en/plugin__lightspeed-console-plugin.json
  src/attachments.ts
  src/components/AttachLogModal.tsx
  src/components/ErrorBoundary.tsx
  src/components/Feedback.tsx
  src/components/GeneralPage.tsx
  src/components/Popover.tsx
  src/components/ReadinessAlert.tsx
  src/hooks/useAlertExtension.ts
  src/hooks/useLocationContext.ts
Labels: lgtm, jira/valid-reference, approved

#304 OLS-791: Remove references to yarn and replace with npm
  README.md
  package.json
  start-console.sh
  test-frontend.sh
  test-prow-e2e.sh
  yarn.lock
Labels: lgtm, jira/valid-reference, approved

#313 Upgrade @typescript-eslint packages and address new type errors
  package-lock.json
  package.json
  src/components/ErrorBoundary.tsx
  src/redux-actions.ts
Labels: lgtm, approved

#315 Remove Helm charts, which are no longer maintained
  README.md
  charts/openshift-console-plugin/.helmignore
  charts/openshift-console-plugin/Chart.yaml
  charts/openshift-console-plugin/templates/_helpers.tpl
  charts/openshift-console-plugin/templates/configmap.yaml
  charts/openshift-console-plugin/templates/consoleplugin.yaml
  charts/openshift-console-plugin/templates/deployment.yaml
  charts/openshift-console-plugin/templates/patch-consoles-job.yaml
  charts/openshift-console-plugin/templates/patcher-clusterrole.yaml
  charts/openshift-console-plugin/templates/patcher-clusterrolebinding.yaml
  charts/openshift-console-plugin/templates/patcher-serviceaccount.yaml
  charts/openshift-console-plugin/templates/service.yaml
  charts/openshift-console-plugin/templates/serviceaccount.yaml
  charts/openshift-console-plugin/values.yaml
  ct.yaml
  install_helm.sh
Labels: lgtm, approved

#316 Remove Cypress tests since they will be added in a separate repository
  integration-tests/.eslintrc
  integration-tests/cypress.config.js
  integration-tests/fixtures/example.json
  integration-tests/plugins/index.ts
  integration-tests/reporter-config.json
  integration-tests/support/index.ts
  integration-tests/support/login.ts
  integration-tests/tests/example-page.cy.ts
  integration-tests/tsconfig.json
  package.json
  test-prow-e2e.sh
Labels: lgtm, approved

#317 Change the floating button to a <Button> element for accessibility
  src/components/Popover.tsx
Labels: lgtm, approved

#318 Change "OpenShift Lightspeed version" to "0.1.1"
  src/components/OverviewDetail.tsx
Labels: lgtm, approved

#325 Upgrade semver dependencies
  package-lock.json
Labels: lgtm, approved

#328 Upgrade typescript-eslint packages to v8.1.0
  package-lock.json
  package.json
Labels: lgtm, approved

#329 Move dependencies for parsing i18n strings to devDependencies
  package-lock.json
  package.json
Labels: lgtm, approved

#331 OLS 0.1.2 version update
  src/components/OverviewDetail.tsx
Labels: lgtm, approved

#332 OLS-472: Change floating button to single color version to support dark theme
  src/components/popover.css
Labels: lgtm, jira/valid-reference, approved

#324 fix(KONFLUX-3663): format PipelineRun files and upload SAST results
  .tekton/lightspeed-console-pull-request.yaml
  .tekton/lightspeed-console-push.yaml
Labels: lgtm, ok-to-test, approved

#335 konflux: avoid nudging yaml files in lightspeed-catalog.* directories
  .tekton/lightspeed-console-push.yaml
Labels: lgtm, approved

#338 Improve widths of popover UI and attachment modal on small screens
  .stylelintrc.yaml
  src/components/general-page.css
  src/components/popover.css
Labels: lgtm, approved

#340 OLS 0.1.3 version update
  src/components/OverviewDetail.tsx
Labels: lgtm, approved

#341 OLS-927: Apply dark theme to code editor
  src/components/AttachmentModal.tsx
Labels: lgtm, jira/valid-reference, approved

#344 Upgrade typescript-eslint packages to v8.2.0
  package-lock.json
  package.json
Labels: lgtm, approved

#345 Revert nudge configs
  .tekton/lightspeed-console-push.yaml
Labels: lgtm, approved

#288 OLS-860: Fix display of OLS API error messages
  src/components/Feedback.tsx
  src/components/GeneralPage.tsx
  src/error.ts
  src/types.ts
Labels: lgtm, jira/valid-reference, approved

#349 OLS 0.1.4 version update
  src/components/OverviewDetail.tsx
Labels: lgtm, approved

#353 Change build-i18n.sh to only search for files in src/ dir
  i18n-scripts/build-i18n.sh
  i18n-scripts/lexers.js
Labels: lgtm, approved

#354 OLS-472: Use multicolor logo in light theme and monocolor in dark theme
  src/assets/logo-dark.svg
  src/components/general-page.css
  src/components/popover.css
Labels: lgtm, jira/valid-reference, approved

#362 Upgrade Webpack to v5.94.0
  package-lock.json
  package.json
Labels: lgtm, approved

#363 Removed sbom-json-check from Konflux pipelines
  .tekton/lightspeed-console-pull-request.yaml
  .tekton/lightspeed-console-push.yaml
Labels: lgtm, approved

#364 Upgrade PatternFly packages to v5.4.0
  package-lock.json
  package.json
Labels: lgtm, approved

#365 Fix floating button background to not be transparent
  src/components/popover.css
Labels: lgtm, approved

#366 OLS-989: Fix to hide Edit button for attachments in chat history
  src/components/AttachmentModal.tsx
  src/components/GeneralPage.tsx
  src/types.ts
Labels: lgtm, jira/valid-reference, approved

#367 Upgrade @typescript-eslint packages to v8.3.0
  package-lock.json
  package.json
Labels: lgtm, approved

#368 Set specific package versions to match those used by plugin SDK v1.0.0
  package-lock.json
  package.json
Labels: lgtm, approved

#370 OLS-711: Add attach logs functionality to more k8s resource types
  locales/en/plugin__lightspeed-console-plugin.json
  src/components/AttachEventsModal.tsx
  src/components/AttachLogModal.tsx
  src/components/AttachmentModal.tsx
  src/components/GeneralPage.tsx
  src/redux-actions.ts
  src/redux-reducers.ts
  src/types.ts
Labels: lgtm, jira/valid-reference, approved

#372 OLS-997: Fix attachment save with wrong value after revert
  src/components/AttachmentModal.tsx
Labels: lgtm, jira/valid-reference, approved

#373 OLS-1000: Fix attach events and attach logs modals to call onClose on unmount
  locales/en/plugin__lightspeed-console-plugin.json
  src/components/AttachEventsModal.tsx
  src/components/AttachLogModal.tsx
  src/components/GeneralPage.tsx
Labels: lgtm, jira/valid-reference, approved
