Repository openshift/lightspeed-console, pull requests merged in 2025-09, with the labels that each got.

#891 OLS-2054: Limit npm memory usage
  Dockerfile
Labels: lgtm, jira/valid-reference, approved

#896 Simplify OLS API setup for development environment
  .env.example
  README.md
  cypress/support/commands.ts
  package-lock.json
  package.json
  src/components/AttachLogModal.tsx
  src/components/AttachMenu.tsx
  src/components/Feedback.tsx
  src/components/GeneralPage.tsx
  src/components/Popover.tsx
  src/components/ReadinessAlert.tsx
  src/config.ts
  src/hooks/useAuth.ts
  webpack.config.ts
Labels: lgtm, approved

#899 OLS-972: Add the ability to attach pod logs from the CronJob details page
  locales/en/plugin__lightspeed-console-plugin.json
  src/components/AttachLogModal.tsx
  src/components/AttachMenu.tsx
Labels: lgtm, jira/valid-reference, approved

#915 Add more Dependabot package groups to reduce volume of PRs a little
  .github/dependabot.yml
Labels: lgtm, approved

#909 OLS-2089: Reduce noise in e2e test logs
  .tekton/integration-tests/lightspeed-console-pre-commit-417.yaml
Labels: lgtm, jira/valid-reference, approved

#927 Set memory for `npm ci` for e2e tests
  .tekton/integration-tests/lightspeed-console-pre-commit-417.yaml
Labels: lgtm, approved

#926 OLS-1559: Warn about large total prompt attachments size
  locales/en/plugin__lightspeed-console-plugin.json
  src/components/AttachMenu.tsx
  src/components/AttachmentLabel.tsx
  src/components/AttachmentsSizeAlert.tsx
  src/components/GeneralPage.tsx
Labels: lgtm, jira/valid-reference, approved

#928 OLS-2124,OLS-2125: Support attaching k8s resource details from the ACM search page
  src/hooks/useLocationContext.ts
  tests/tests/lightspeed-install.cy.ts
Labels: lgtm, jira/valid-reference, approved

#934 Updated konflux files
  .tekton/lightspeed-console-pf5-pull-request.yaml
  .tekton/lightspeed-console-pf5-push.yaml
  .tekton/lightspeed-console-pull-request.yaml
  .tekton/lightspeed-console-push.yaml
Labels: lgtm, ok-to-test, approved
